name: CMake Worker

on:
  push:
    branches: [ "version-core" ]
  pull_request:
    branches: [ "version-core" ]

jobs:
  release:  
    name: Release
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Check if Git is installed
        run: git --version
    
      - name: Check if directory is a Git repository
        run: git rev-parse --is-inside-work-tree
        id: check_git_repo
        continue-on-error: true
    
      - name: Check Commit Message
        id: check_commit_message
        run: echo ::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})

      - name: Release Condition
        if: startsWith(steps.check_commit_message.outputs.message, '[release]')
        id: release_condition
        run: exit 0

      - name: Install Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Linux Install Libraries
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list

          sudo apt-get update
          sudo apt-get install gcc-mingw-w64 g++-mingw-w64 mingw-w64-tools mingw-w64-x86-64-dev
          sudo apt-get install libfreetype6-dev vulkan-sdk libsdl2-dev libglew-dev libopengl-dev libglx-dev libgl1-mesa-dev

          wget https://github.com/libsdl-org/SDL/releases/download/release-2.30.2/SDL2-devel-2.30.2-mingw.zip
          unzip ./SDL2-devel-2.30.2-mingw.zip

          sudo cp -r ./SDL2-2.30.2/x86_64-w64-mingw32/* /usr/x86_64-w64-mingw32
          sudo cp -r ${{ github.workspace }}/x86_64-w64-mingw32/* /usr/x86_64-w64-mingw32/

      - name: Configure Linux-CMake
        run: >
          cmake -B ${{ github.workspace }}/cmake-build-debug
          -S ${{ github.workspace }}
          -G Ninja
          -DCMAKE_CXX_COMPILER=g++
          -DEKG_ENABLE_TEST=0
          -DEKG_LINUX_NOT_FOUND_FREETYPE=1

      - name: Build Linux-CMake
        run: |
          cmake --build ${{ github.workspace }}/cmake-build-debug
          sudo rm -r -f ${{ github.workspace }}/cmake-build-debug

      - name: Configure Windows-CMake
        run: >
          cmake -B ${{ github.workspace }}/cmake-build-debug
          -S ${{ github.workspace }}
          -G Ninja
          -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++
          -DEKG_ENABLE_TEST=0
          -DEKG_LINUX_NOT_FOUND_FREETYPE=1

      - name: Build Windows-CMake
        run: |
          cmake --build ${{ github.workspace }}/cmake-build-debug
